cmake_minimum_required(VERSION 3.14)

include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/AndroidNdk.cmake)

set(CC ${JONES_CC_COMPILER})
set(CXX ${JONES_CXX_COMPILER})
set(ARCH_NAME ${ANDROID_LLVM_TRIPLE})

set(JONES_DIR_ROOT_OUT ${CMAKE_CURRENT_SOURCE_DIR}/out/android/${CMAKE_BUILD_TYPE}/${CMAKE_ANDROID_ARCH_ABI})

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${JONES_DIR_ROOT_OUT}/${CMAKE_PROJECT_NAME}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${JONES_DIR_ROOT_OUT}/${CMAKE_PROJECT_NAME}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${JONES_DIR_ROOT_OUT}/${CMAKE_PROJECT_NAME}/bin)

set(EXTERNAL_PROJECTS
    cppcoro
    boost
    gsl
    zlib
    png
    gzip
    spdlog)
