if(ANDROID)

  set(JONES_DIR_ROOT_OUT ${CMAKE_CURRENT_SOURCE_DIR}/out/android/${CMAKE_BUILD_TYPE}/${CMAKE_ANDROID_ARCH_ABI})

  set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${JONES_DIR_ROOT_OUT}/${CMAKE_PROJECT_NAME}/lib)

  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${JONES_DIR_ROOT_OUT}/${CMAKE_PROJECT_NAME}/lib)

  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${JONES_DIR_ROOT_OUT}/${CMAKE_PROJECT_NAME}/bin)

  set(EXTERNAL_PROJECTS
      boost
      capstone
      gsl
      zlib
      png
      gzip
      cppcoro)

endif()
