cmake_minimum_required(VERSION 3.14)

set(CC ${CMAKE_C_COMPILER})
set(CXX ${CMAKE_CXX_COMPILER})
set(ARCH_NAME ${CMAKE_SYSTEM_PROCESSOR})

set(JONES_DIR_ROOT_OUT ${CMAKE_CURRENT_SOURCE_DIR}/out/default)

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${JONES_DIR_ROOT_OUT}/${CMAKE_PROJECT_NAME}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${JONES_DIR_ROOT_OUT}/${CMAKE_PROJECT_NAME}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${JONES_DIR_ROOT_OUT}/${CMAKE_PROJECT_NAME}/bin)

set(EXTERNAL_PROJECTS
    ncurses
    sndio
    sdl
    boost
    capstone
    gsl
    zlib
    png
    gzip
    spdlog
    cppcoro)
