cmake_minimum_required(VERSION 3.14)

if(ANDROID_ABI STREQUAL armeabi-v7a)
  set(JONES_COMPILER_TARGET "armv7a-linux-androideabi${ANDROID_NATIVE_API_LEVEL}")
elseif(ANDROID_ABI STREQUAL arm64-v8a)
  set(JONES_COMPILER_TARGET "aarch64-linux-android${ANDROID_NATIVE_API_LEVEL}")
elseif(ANDROID_ABI STREQUAL x86)
  set(JONES_COMPILER_TARGET "i686-linux-android${ANDROID_NATIVE_API_LEVEL}")
elseif(ANDROID_ABI STREQUAL x86_64)
  set(JONES_COMPILER_TARGET "x86_64-linux-android${ANDROID_NATIVE_API_LEVEL}")
endif()

set(JONES_CXX_COMPILER ${ANDROID_TOOLCHAIN_ROOT}/bin/${JONES_COMPILER_TARGET}-clang++)
set(JONES_CC_COMPILER ${ANDROID_TOOLCHAIN_ROOT}/bin/${JONES_COMPILER_TARGET}-clang)
